### PR TITLE
Add external-search feature which accepts a model from anywhere to search with.

### PR DESCRIPTION
**Pull request by gregbenner**
Add external-search feature which accepts a model from anywhere to search with.
<input ng-model="searchModel" /> <rb-table external-search="searchModel"></rb-table>

### CODE REVIEW

**Comment by gregbenner** [comment]
Waiting till develop branch is safe again to merge, reviews welcome.

**Comment by nwhite89** [comment]
@gregbenner could you add test for this please as well.

**Comment by gregbenner** [comment]
:sob: Yeah, will do.

**Comment by gregbenner** [comment]
Added tests and semicolon's ready for some review action.

**Comment by gregbenner** [comment]
TP: https://rockabox.tpondemand.com/entity/10227

**Comment by jess0407** [comment]
Have tested with Move search box into header instead of inside the rb-table #299.
It looks good to me.

**Pull request merged**
