### PR TITLE
Add ability to one or more css class on the table. Add css to apply a fixed layout table.

### PR DESCRIPTION
**Pull request by gregbenner**
Add ability to one or more css class on the table. Add css to apply a fixed layout table.

TP: https://rockabox.tpondemand.com/entity/12051

Afterwards this PR would like a look, I mean since you are here and all: https://github.com/rockabox/rbx_campaign_management/pull/377

### CODE REVIEW

**Comment by gregbenner** [comment]
Just checking some tables have one or two columns holding badges.. going to adjust.

**Comment by gregbenner** [comment]
@rockabox/frontend I am ready for scrutiny.

**Comment by nwhite89** [comment]
@gregbenner looks by me @rockabox/qa over to you :+1:

**Comment by jim-dj** [comment]
Ready to merge to develop for QA

**Pull request merged**
